name: "gueyeb"
profile:
  web: "http://gueyeb.github.io"
  twitter: "babttz"
  gravatar: "19535b8b4be905d5cecdc67b3864bd0d"
hasbeen:
  cities:
    - "Beijing"
    - "Bordeaux"
    - "Dakar"
    - "Milan"
    - "Paris"
    - "Thies"
    - "Rufisque"
