name: "nerdbabe"
profile:
  web: "http://nerdbabe.de"
  twitter: "nerdbabe"
  gravatar: "5a536d00a2ce1f03f2726a83cfdc6ab8"
hasbeen:
  cities:
    - "Aabenraa"
    - "Aachen"
    - "Aalborg"
    - "Aarhus"
    - "Aberdeen"
    - "Amsterdam"
    - "Aschaffenburg"
    - "Augsburg"
    - "Bamberg"
    - "Barcelona"
    - "Berlin"
    - {"Bernau": "Bernau, Österreich"}
    - {"Biarritz": "Biarritz, France"}
    - "Bochum"
    - "Bonn"
    - "Bordeaux"
    - "Bremen"
    - "Brighton"
    - "Broadstairs"
    - "Brussel"
    - "Chemnitz"
    - "Cologne"
    - "Cuxhaven"
    - {"Dax": "Dax, France"}
    - "Dortmund"
    - "Düsseldorf"
    - "Den Haag"
    - "Drammen"
    - "Dresden"
    - "Dundee"
    - "Edinburgh"
    - "Essen"
    - "Fredrikstad"
    - "Frderikshavn"
    - "Faaborg"
    - "Firenze"
    - "Flensburg"
    - "Fredericia"
    - "Fehmarn"
    - "Ghent"
    - "Glasgow"
    - "Gelsenkirchen"
    - "Hamburg"
    - "Hanover"
    - "Heidelberg"
    - "Helgoland"
    - "Inverness"
    - "Jessheim"
    - "Katwijk"
    - "Kiel"
    - "Kitzbühel"
    - "Kopenhagen"
    - "Leipzig"
    - {"Le Porge": "Le Porge, France"}
    - "London"
    - "Lucca"
    - "Lüneburg"
    - "Margate"
    - "Middelfart"
    - "Middelburg"
    - "Monschau"
    - "Munich"
    - "Munster"
    - "Nordby"
    - "Neuss"
    - "Nuremberg"
    - "Oslo"
    - "Otterndorf"
    - "Odense"
    - "Oldenburg"
    - "Passau"
    - "Paris"
    - "Pisa"
    - "Poznan"
    - "Potsdam"
    - "Ravensburg"
    - "Rosenheim"
    - "Rostock"
    - "Rotterdam"
    - "San Gimignano"
    - "Skagen"
    - "Stavanger"
    - "Stade"
    - {"Saint-Girons Plage": "Saint-Girons Plage, France"}
    - "Stuttgart"
    - "Ulm"
    - "Vienna"
    - "Volterra"
    - "Würzburg"
