name: "Rin Raeuber"
profile:
  web: "http://rin.li"
  twitter: "rinpaku"
  gravatar: "92dc402905776c15aa4917ec348aeb72"
hasbeen:
  cities:
    - "Alcúdia"
    - "Amsterdam"
    - "Barcelona"
    - "Berlin"
    - "Brighton"
    - "Braga"
    - "Copenhagen"
    - "Essen"
    - "Göteborg"
    - "London"
    - "Milano"
    - "München"
    - "Stockholm"
    - "Zurich"
