name: "Rin Raeuber"
profile:
  web: "http://rin.li"
  twitter: "rinpaku"
  gravatar: "67d3014fe6c86362a4c4ed0586827bb8"
hasbeen:
  cities:
    - "Alcúdia"
    - "Amsterdam"
    - "Berlin"
    - "Brighton"
    - "Braga"
    - "Copenhagen"
    - "Essen"
    - "Göteborg"
    - "London"
    - "München"
    - "Zurich"
